1. Создать (используя модуль numpy и pandas) три файла *.csv, содержащих 5 полей:
дата, id, пол, профессия, доход. В каждом из файлов используя 1000 уникальных id,
4 уникальных профессии, 2 пола, 3 года с гранулярностью день, получить 1 млн. строк.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df0=pd.DataFrame({'sex':np.random.choice(['муж','жен'],p=(0.65,0.35),size=1000),
'id':np.array(range(1000))})
df0[:5]

   sex  id
0  муж   0
1  муж   1
2  муж   2
3  жен   3
4  муж   4

In [ ]:
df0['profession']=[x for x in np.random.choice(['специалист','старший специалист','руководитель отдела','директор'],size=(1000,3000))]
df0[:5]

   sex  id                                         profession
0  муж   0  [директор, директор, директор, специалист, ста...
1  муж   1  [директор, директор, директор, старший специал...
2  муж   2  [специалист, специалист, старший специалист, р...
3  жен   3  [директор, директор, директор, руководитель от...
4  муж   4  [руководитель отдела, руководитель отдела, ста...

In [ ]:
df1=df0.explode('profession')
df1['DATE']=list(pd.date_range('2010-01-01',periods=3000,freq='D'))*1000
df1['income']=list(np.random.normal(100000,20000,size=3000))*1000
df1

     sex   id           profession       DATE         income
0    муж    0             директор 2010-01-01   68253.507451
0    муж    0             директор 2010-01-02  127908.155859
0    муж    0             директор 2010-01-03   90367.792574
0    муж    0           специалист 2010-01-04  123680.156832
0    муж    0   старший специалист 2010-01-05  148652.038036
..   ...  ...                  ...        ...            ...
999  муж  999           специалист 2018-03-15  116370.664501
999  муж  999             директор 2018-03-16  114795.448211
999  муж  999   старший специалист 2018-03-17   94428.640377
999  муж  999             директор 2018-03-18   99633.493724
999  муж  999  руководитель отдела 2018-03-19  145003.696622

[3000000 rows x 5 columns]

In [ ]:
del df0

In [ ]:
df2=df1.sample(1000000)
df2.to_csv('/content/df1.csv',sep=';',index=False,mode='w')

In [ ]:
df1.index=range(3000000)
df1

         sex   id           profession       DATE         income
0        муж    0             директор 2010-01-01   68253.507451
1        муж    0             директор 2010-01-02  127908.155859
2        муж    0             директор 2010-01-03   90367.792574
3        муж    0           специалист 2010-01-04  123680.156832
4        муж    0   старший специалист 2010-01-05  148652.038036
...      ...  ...                  ...        ...            ...
2999995  муж  999           специалист 2018-03-15  116370.664501
2999996  муж  999             директор 2018-03-16  114795.448211
2999997  муж  999   старший специалист 2018-03-17   94428.640377
2999998  муж  999             директор 2018-03-18   99633.493724
2999999  муж  999  руководитель отдела 2018-03-19  145003.696622

[3000000 rows x 5 columns]

In [ ]:
df3=df1[~df1.index.isin(df2.index)].sample(1000000)
df3.to_csv('/content/df2.csv',sep=';',index=False,mode='w')

In [ ]:
df4=df1[~((df1.index.isin(df2.index))|(df1.index.isin(df3.index)))]
df4.to_csv('/content/df3.csv',sep=';',index=False,mode='w')

получить среднее значение дохода для каждого пола, в каждом месяце каждого года из выборки

2. Используя инкрементную обработку 
3. Используя Spark

In [ ]:
del df1,df2,df3,df4

In [ ]:
import os

pathl=['/content/'+x for x in os.listdir('/content/') if x.find('csv')>-1]

In [ ]:
d=dict()
d['e']=5
d.update({'е':6})
d

{'e': 5, 'е': 6}

In [ ]:
d.update({'rr':6},)
d

{'e': 5, 'е': 6, 'rr': 6}

In [ ]:
d={'муж':[{'sum':330},{'cnt':20}]}
d

{'муж': [{'sum': 330}, {'cnt': 20}]}

In [ ]:
d.keys()

dict_keys(['муж'])

In [ ]:
d['муж'][0]['sum']

330

In [ ]:
dct=dict()
for path in pathl:
  with open(path) as fl:
    for line in fl.readlines()[1:]:
       #print(line)
       key=line.split(';')[0]+''.join(line.split(';')[3].split('-')[:2])
       value=float(line.split(';')[-1])
       try:
         dct[key]=[{'sum':dct[key][0]['sum']+value},{'cnt':dct[key][1]['cnt']+1}]
       except:
         dct.update({key:[{'sum':value},{'cnt':1}]})
dct

{'муж201302': [{'sum': 1741194594.6898642}, {'cnt': 17528}],
 'муж201208': [{'sum': 1956309586.143083}, {'cnt': 19406}],
 'жен201302': [{'sum': 1040266419.1916931}, {'cnt': 10472}],
 'муж201101': [{'sum': 1900122407.037028}, {'cnt': 19406}],
 'муж201701': [{'sum': 1943314642.5029542}, {'cnt': 19406}],
 'жен201801': [{'sum': 1164672290.5839295}, {'cnt': 11594}],
 'жен201006': [{'sum': 1230080412.2998064}, {'cnt': 11220}],
 'муж201802': [{'sum': 1820516173.7940512}, {'cnt': 17528}],
 'жен201312': [{'sum': 1146433024.1695392}, {'cnt': 11594}],
 'жен201410': [{'sum': 1183895978.6504197}, {'cnt': 11594}],
 'муж201402': [{'sum': 1700563291.5485706}, {'cnt': 17528}],
 'муж201401': [{'sum': 2075956914.6322582}, {'cnt': 19406}],
 'муж201307': [{'sum': 2070472413.9868453}, {'cnt': 19406}],
 'муж201601': [{'sum': 1880734399.6564367}, {'cnt': 19406}],
 'муж201008': [{'sum': 1971202155.4683867}, {'cnt': 19406}],
 'муж201508': [{'sum': 1900226773.206364}, {'cnt': 19406}],
 'муж201308': [{'sum': 1842577598.8837168}, {'cnt': 19406}],
 'муж201204': [{'sum': 1801156885.7720678}, {'cnt': 18780}],
 'жен201803': [{'sum': 732321860.1301965}, {'cnt': 7106}],
 'жен201212': [{'sum': 1099573985.7252285}, {'cnt': 11594}],
 'муж201405': [{'sum': 2115084339.1383045}, {'cnt': 19406}],
 'муж201110': [{'sum': 1937458504.5633504}, {'cnt': 19406}],
 'жен201401': [{'sum': 1240268188.6142116}, {'cnt': 11594}],
 'жен201201': [{'sum': 1157725185.132679}, {'cnt': 11594}],
 'муж201002': [{'sum': 1752771934.9266176}, {'cnt': 17528}],
 'муж201407': [{'sum': 1976224755.521518}, {'cnt': 19406}],
 'муж201112': [{'sum': 2000399374.043282}, {'cnt': 19406}],
 'муж201010': [{'sum': 2061049086.900638}, {'cnt': 19406}],
 'жен201406': [{'sum': 1116327445.3546977}, {'cnt': 11220}],
 'муж201507': [{'sum': 2011525830.1298528}, {'cnt': 19406}],
 'жен201005': [{'sum': 1157201056.5182898}, {'cnt': 11594}],
 'муж201509': [{'sum': 1865630895.1386287}, {'cnt': 18780}],
 'муж201501': [{'sum': 1845300631.9955049}, {'cnt': 19406}],
 'жен201008': [{'sum': 1177683076.9092565}, {'cnt': 11594}],
 'муж201311': [{'sum': 1945306702.3742125}, {'cnt': 18780}],
 'муж201104': [{'sum': 1876587261.8334873}, {'cnt': 18780}],
 'муж201211': [{'sum': 1860791822.837448}, {'cnt': 18780}],
 'муж201512': [{'sum': 1948682195.1157866}, {'cnt': 19406}],
 'жен201202': [{'sum': 1130071126.473256}, {'cnt': 10846}],
 'жен201208': [{'sum': 1168785599.388998}, {'cnt': 11594}],
 'муж201403': [{'sum': 1928999962.5544007}, {'cnt': 19406}],
 'жен201704': [{'sum': 1083606863.758592}, {'cnt': 11220}],
 'жен201502': [{'sum': 1058129655.7567567}, {'cnt': 10472}],
 'муж201304': [{'sum': 1856304323.1835742}, {'cnt': 18780}],
 'жен201409': [{'sum': 1113108434.5009398}, {'cnt': 11220}],
 'жен201205': [{'sum': 1118599609.7396774}, {'cnt': 11594}],
 'жен201508': [{'sum': 1135279254.279851}, {'cnt': 11594}],
 'жен201708': [{'sum': 1127424242.3896565}, {'cnt': 11594}],
 'жен201308': [{'sum': 1100837095.8188407}, {'cnt': 11594}],
 'муж201310': [{'sum': 1928437380.1952665}, {'cnt': 19406}],
 'жен201703': [{'sum': 1100006199.5264702}, {'cnt': 11594}],
 'муж201609': [{'sum': 1771233700.961453}, {'cnt': 18780}],
 'жен201408': [{'sum': 1180654751.511766}, {'cnt': 11594}],
 'муж201603': [{'sum': 1966208446.2629464}, {'cnt': 19406}],
 'муж201409': [{'sum': 1863117326.1969814}, {'cnt': 18780}],
 'муж201602': [{'sum': 1692832335.7511032}, {'cnt': 18154}],
 'муж201710': [{'sum': 2021176811.8926356}, {'cnt': 19406}],
 'муж201412': [{'sum': 2027214711.3714447}, {'cnt': 19406}],
 'жен201607': [{'sum': 1152892048.932005}, {'cnt': 11594}],
 'муж201209': [{'sum': 1821843029.6719875}, {'cnt': 18780}],
 'муж201306': [{'sum': 1920277069.403784}, {'cnt': 18780}],
 'жен201509': [{'sum': 1114610151.4086783}, {'cnt': 11220}],
 'жен201510': [{'sum': 1184693446.2427273}, {'cnt': 11594}],
 'муж201312': [{'sum': 1918895917.4602797}, {'cnt': 19406}],
 'муж201604': [{'sum': 1820628153.450705}, {'cnt': 18780}],
 'жен201507': [{'sum': 1201774218.0008404}, {'cnt': 11594}],
 'муж201404': [{'sum': 1924458114.8929632}, {'cnt': 18780}],
 'жен201107': [{'sum': 1135607829.3767567}, {'cnt': 11594}],
 'жен201705': [{'sum': 1162369911.5740938}, {'cnt': 11594}],
 'муж201410': [{'sum': 1981601290.4683433}, {'cnt': 19406}],
 'муж201207': [{'sum': 1929629402.4950283}, {'cnt': 19406}],
 'муж201707': [{'sum': 2076101085.7701879}, {'cnt': 19406}],
 'жен201611': [{'sum': 1106082662.020281}, {'cnt': 11220}],
 'муж201206': [{'sum': 1868585848.5695724}, {'cnt': 18780}],
 'муж201607': [{'sum': 1929707012.3834515}, {'cnt': 19406}],
 'жен201711': [{'sum': 1075410339.6282816}, {'cnt': 11220}],
 'жен201106': [{'sum': 1090759130.1977077}, {'cnt': 11220}],
 'муж201203': [{'sum': 1956688388.709562}, {'cnt': 19406}],
 'муж201205': [{'sum': 1872308437.6925895}, {'cnt': 19406}],
 'жен201311': [{'sum': 1162211991.5143278}, {'cnt': 11220}],
 'муж201003': [{'sum': 1847574599.576729}, {'cnt': 19406}],
 'жен201609': [{'sum': 1058213105.6862699}, {'cnt': 11220}],
 'муж201706': [{'sum': 1962380434.326162}, {'cnt': 18780}],
 'жен201610': [{'sum': 1139698659.2899094}, {'cnt': 11594}],
 'муж201103': [{'sum': 1993235233.0827563}, {'cnt': 19406}],
 'муж201111': [{'sum': 1950405512.6811936}, {'cnt': 18780}],
 'муж201305': [{'sum': 1913260428.4581475}, {'cnt': 19406}],
 'жен201012': [{'sum': 1165689749.2161882}, {'cnt': 11594}],
 'муж201109': [{'sum': 1809723569.6301117}, {'cnt': 18780}],
 'жен201011': [{'sum': 1118389980.2605467}, {'cnt': 11220}],
 'жен201105': [{'sum': 1104366055.063813}, {'cnt': 11594}],
 'муж201006': [{'sum': 2058904647.3254035}, {'cnt': 18780}],
 'жен201501': [{'sum': 1102463955.8567386}, {'cnt': 11594}],
 'жен201707': [{'sum': 1240354322.808317}, {'cnt': 11594}],
 'жен201602': [{'sum': 1011372673.4359847}, {'cnt': 10846}],
 'жен201101': [{'sum': 1135216901.328907}, {'cnt': 11594}],
 'жен201206': [{'sum': 1116375570.8706255}, {'cnt': 11220}],
 'муж201108': [{'sum': 1864836356.5450616}, {'cnt': 19406}],
 'муж201510': [{'sum': 1982936089.1655343}, {'cnt': 19406}],
 'муж201106': [{'sum': 1825709132.363046}, {'cnt': 18780}],
 'муж201201': [{'sum': 1937796700.2488656}, {'cnt': 19406}],
 'муж201610': [{'sum': 1907623959.132328}, {'cnt': 19406}],
 'жен201702': [{'sum': 1107220467.142887}, {'cnt': 10472}],
 'жен201404': [{'sum': 1149756126.150166}, {'cnt': 11220}],
 'жен201412': [{'sum': 1211147447.3688412}, {'cnt': 11594}],
 'жен201207': [{'sum': 1152845681.3629243}, {'cnt': 11594}],
 'муж201803': [{'sum': 1225757979.7900913}, {'cnt': 11894}],
 'жен201606': [{'sum': 1121507153.5537243}, {'cnt': 11220}],
 'муж201303': [{'sum': 2038691016.5004342}, {'cnt': 19406}],
 'жен201103': [{'sum': 1190846608.902414}, {'cnt': 11594}],
 'жен201010': [{'sum': 1231361595.0492775}, {'cnt': 11594}],
 'муж201102': [{'sum': 1805675379.2461474}, {'cnt': 17528}],
 'жен201309': [{'sum': 1154694054.9897342}, {'cnt': 11220}],
 'муж201505': [{'sum': 1947284622.01314}, {'cnt': 19406}],
 'муж201709': [{'sum': 1853856286.798975}, {'cnt': 18780}],
 'жен201003': [{'sum': 1103822524.347696}, {'cnt': 11594}],
 'муж201309': [{'sum': 1932723204.3412695}, {'cnt': 18780}],
 'жен201407': [{'sum': 1180683799.624674}, {'cnt': 11594}],
 'жен201009': [{'sum': 1103875300.4504597}, {'cnt': 11220}],
 'муж201605': [{'sum': 1778651337.818878}, {'cnt': 19406}],
 'жен201505': [{'sum': 1163393687.9120176}, {'cnt': 11594}],
 'муж201506': [{'sum': 1817634032.8809593}, {'cnt': 18780}],
 'жен201102': [{'sum': 1078790082.8084712}, {'cnt': 10472}],
 'муж201504': [{'sum': 1858328861.8771038}, {'cnt': 18780}],
 'жен201305': [{'sum': 1143066134.5739832}, {'cnt': 11594}],
 'жен201209': [{'sum': 1088449349.9956508}, {'cnt': 11220}],
 'жен201403': [{'sum': 1152469626.1907518}, {'cnt': 11594}],
 'жен201604': [{'sum': 1087723529.377947}, {'cnt': 11220}],
 'муж201502': [{'sum': 1771094022.7372835}, {'cnt': 17528}],
 'муж201105': [{'sum': 1848484359.5453854}, {'cnt': 19406}],
 'жен201303': [{'sum': 1218003898.036943}, {'cnt': 11594}],
 'жен201601': [{'sum': 1123633650.9130297}, {'cnt': 11594}],
 'муж201001': [{'sum': 1954499059.629558}, {'cnt': 19406}],
 'жен201612': [{'sum': 1163986589.242789}, {'cnt': 11594}],
 'муж201712': [{'sum': 1937377024.146388}, {'cnt': 19406}],
 'муж201703': [{'sum': 1841186847.3356645}, {'cnt': 19406}],
 'муж201711': [{'sum': 1800018375.9554021}, {'cnt': 18780}],
 'жен201310': [{'sum': 1152133514.6855464}, {'cnt': 11594}],
 'муж201408': [{'sum': 1976176134.8832464}, {'cnt': 19406}],
 'муж201005': [{'sum': 1936919415.4557738}, {'cnt': 19406}],
 'жен201210': [{'sum': 1189724722.2137506}, {'cnt': 11594}],
 'муж201301': [{'sum': 1941314910.0081606}, {'cnt': 19406}],
 'жен201709': [{'sum': 1107575481.2505069}, {'cnt': 11220}],
 'муж201007': [{'sum': 1910042747.881813}, {'cnt': 19406}],
 'жен201608': [{'sum': 1144778006.4422617}, {'cnt': 11594}],
 'муж201503': [{'sum': 1924959304.771183}, {'cnt': 19406}],
 'жен201109': [{'sum': 1081208650.2262752}, {'cnt': 11220}],
 'муж201704': [{'sum': 1813737691.7457354}, {'cnt': 18780}],
 'жен201307': [{'sum': 1236991506.1198444}, {'cnt': 11594}],
 'жен201405': [{'sum': 1263644637.1209936}, {'cnt': 11594}],
 'жен201605': [{'sum': 1062644728.9845967}, {'cnt': 11594}],
 'муж201009': [{'sum': 1847662936.0482354}, {'cnt': 18780}],
 'муж201011': [{'sum': 1871957560.5430799}, {'cnt': 18780}],
 'муж201406': [{'sum': 1868505296.2353792}, {'cnt': 18780}],
 'жен201710': [{'sum': 1207540140.012519}, {'cnt': 11594}],
 'муж201708': [{'sum': 1887079079.5075269}, {'cnt': 19406}],
 'муж201411': [{'sum': 1840319492.1805234}, {'cnt': 18780}],
 'муж201004': [{'sum': 1849775691.5026653}, {'cnt': 18780}],
 'жен201712': [{'sum': 1157474452.1257017}, {'cnt': 11594}],
 'жен201111': [{'sum': 1165258245.5954678}, {'cnt': 11220}],
 'жен201306': [{'sum': 1147258185.2348998}, {'cnt': 11220}],
 'жен201007': [{'sum': 1141143750.331887}, {'cnt': 11594}],
 'жен201411': [{'sum': 1099488003.31545}, {'cnt': 11220}],
 'жен201110': [{'sum': 1157523132.1192384}, {'cnt': 11594}],
 'жен201706': [{'sum': 1172412591.753962}, {'cnt': 11220}],
 'муж201801': [{'sum': 1949424743.0629325}, {'cnt': 19406}],
 'жен201402': [{'sum': 1015991487.2829347}, {'cnt': 10472}],
 'жен201002': [{'sum': 1047183232.687888}, {'cnt': 10472}],
 'жен201301': [{'sum': 1159827118.7588534}, {'cnt': 11594}],
 'жен201503': [{'sum': 1150055559.0805895}, {'cnt': 11594}],
 'муж201702': [{'sum': 1853262065.324791}, {'cnt': 17528}],
 'муж201107': [{'sum': 1900776741.1494014}, {'cnt': 19406}],
 'муж201606': [{'sum': 1877175075.199567}, {'cnt': 18780}],
 'жен201108': [{'sum': 1114135459.0221088}, {'cnt': 11594}],
 'жен201204': [{'sum': 1076090535.588978}, {'cnt': 11220}],
 'муж201608': [{'sum': 1916125754.098578}, {'cnt': 19406}],
 'муж201611': [{'sum': 1851357610.7611935}, {'cnt': 18780}],
 'жен201001': [{'sum': 1167703911.0246892}, {'cnt': 11594}],
 'жен201512': [{'sum': 1164228659.7018096}, {'cnt': 11594}],
 'муж201511': [{'sum': 1889559728.0215154}, {'cnt': 18780}],
 'муж201210': [{'sum': 1991357422.7427676}, {'cnt': 19406}],
 'муж201202': [{'sum': 1891509425.594261}, {'cnt': 18154}],
 'муж201705': [{'sum': 1945571028.4637153}, {'cnt': 19406}],
 'муж201212': [{'sum': 1840463409.2620423}, {'cnt': 19406}],
 'жен201802': [{'sum': 1087656627.7939136}, {'cnt': 10472}],
 'жен201701': [{'sum': 1161021847.118295}, {'cnt': 11594}],
 'жен201603': [{'sum': 1174699614.859924}, {'cnt': 11594}],
 'жен201112': [{'sum': 1195126782.5753942}, {'cnt': 11594}],
 'жен201504': [{'sum': 1110247594.7956524}, {'cnt': 11220}],
 'жен201004': [{'sum': 1105137553.709235}, {'cnt': 11220}],
 'жен201211': [{'sum': 1111719076.263932}, {'cnt': 11220}],
 'жен201104': [{'sum': 1121155967.932536}, {'cnt': 11220}],
 'жен201203': [{'sum': 1169011912.7434433}, {'cnt': 11594}],
 'жен201304': [{'sum': 1109038046.119161}, {'cnt': 11220}],
 'муж201012': [{'sum': 1951127762.0571995}, {'cnt': 19406}],
 'муж201612': [{'sum': 1948277018.3583474}, {'cnt': 19406}],
 'жен201506': [{'sum': 1085934709.7403564}, {'cnt': 11220}],
 'жен201511': [{'sum': 1128906291.1821284}, {'cnt': 11220}]}

In [ ]:
dct['жен201001']

[{'sum': 1167703911.0246892}, {'cnt': 11594}]

In [ ]:
df=pd.DataFrame()
for path in pathl:
  for chunk in pd.read_csv(path,sep=';',chunksize=100000):
    tmp=chunk.groupby([chunk.sex+chunk.DATE.apply(lambda x: x.split('-')[0]+x.split('-')[1])])['income'].agg({'sum','count'})
    df=df.append(tmp.reset_index())
df.groupby(['index']).sum()

                    sum  count
index
жен201001  1.167704e+09  11594
жен201002  1.047183e+09  10472
жен201003  1.103823e+09  11594
жен201004  1.105138e+09  11220
жен201005  1.157201e+09  11594
...                 ...    ...
муж201711  1.800018e+09  18780
муж201712  1.937377e+09  19406
муж201801  1.949425e+09  19406
муж201802  1.820516e+09  17528
муж201803  1.225758e+09  11894

[198 rows x 2 columns]

In [ ]:
df.groupby([df.sex+df.DATE.apply(lambda x: x.split('-')[0]+x.split('-')[1])])['income'].agg({'sum','count'}).reset_index()

         index           sum  count
0    жен201001  1.189623e+09  11745
1    жен201002  1.055746e+09  10536
2    жен201003  1.127240e+09  11772
3    жен201004  1.102709e+09  11166
4    жен201005  1.160219e+09  11619
..         ...           ...    ...
193  муж201711  1.776786e+09  18555
194  муж201712  1.959824e+09  19599
195  муж201801  1.933250e+09  19302
196  муж201802  1.803627e+09  17415
197  муж201803  1.227836e+09  11970

[198 rows x 3 columns]

In [ ]:
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q https://downloads.apache.org/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3.tgz
!tar xf spark-3.3.0-bin-hadoop3.tgz
!pip -q install findspark
!pip -q install pyspark

     |████████████████████████████████| 281.3 MB 32 kB/s
     |████████████████████████████████| 199 kB 48.4 MB/s
  Building wheel for pyspark (setup.py) ... done

In [ ]:
import os
import json
import requests
import pandas as pd
import findspark 
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, IntegerType, StringType, BooleanType,ArrayType,array,Dict
from pyspark.sql.functions import col, asc, desc, length,explode,map_values,udf

In [ ]:
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.3.0-bin-hadoop3"
findspark.init()
spark = SparkSession.builder.master("local[*]").getOrCreate()

In [ ]:
dfs=spark.read.csv('/content/*.csv',header=True,sep=';')

In [ ]:
dfs.count()

3000000

In [ ]:
dfs.withColumn('index',dfs).show(3)

+---+---+------------------+----------+-----------------+----------+
|sex| id|        profession|      DATE|           income|     index|
+---+---+------------------+----------+-----------------+----------+
|муж| 54|старший специалист|2013-02-21|96902.02516922468|2013-02-21|
|муж| 70|        специалист|2012-08-25|90505.62954050553|2012-08-25|
|жен|561|        специалист|2013-02-20|68558.02026990658|2013-02-20|
+---+---+------------------+----------+-----------------+----------+
only showing top 3 rows

In [ ]:
dfs.groupby(['sex','DATE']).agg({'income':'mean'}).show()

+---+----------+------------------+
|sex|      DATE|       avg(income)|
+---+----------+------------------+
|муж|2016-05-02|  92283.1725972633|
|муж|2015-07-10| 82370.77087370852|
|муж|2017-06-22|105100.85680468036|
|муж|2013-07-01|131996.56702154985|
|муж|2011-05-17| 98732.57841604803|
|жен|2014-03-17|105953.76532486269|
|жен|2014-01-21| 95253.13463328083|
|муж|2010-03-13| 94674.51121544433|
|муж|2012-11-29| 85305.47159824347|
|муж|2013-05-02| 57571.26940933244|
|жен|2017-11-08| 77863.50988387397|
|муж|2016-10-29|100237.64457007864|
|жен|2017-06-24|102073.31194614046|
|жен|2012-06-17| 91216.28847182526|
|жен|2013-11-16| 73097.53811940056|
|жен|2011-03-08|51924.767069070316|
|муж|2015-05-16|166574.03287388364|
|жен|2016-04-23|105596.49107818815|
|муж|2012-02-19|  95335.1936801818|
|жен|2013-06-30|110964.25438708268|
+---+----------+------------------+
only showing top 20 rows